### PR TITLE
🩹 SimpleSDMLayers handling of clip with coordinates on cell boundaries

### LINKED ISSUE #149: Add a test for clipping with exact coordinates
Add a test for the fix in #144. This should also test for non-natural values with 0.5 or 0.25 increments

### LINKED ISSUE #150: Avoid using stride when clipping
`clip` currently uses the stride, which might return approximation errors as in #144. 

@tpoisot had an idea to avoid using stride completely. Possibly using indices instead of coordinates?

### LINKED ISSUE #151: Add expand options to clip
Add options like `leftexpand = true` to `clip` to specify if the function should include outside pixels when the clipping coordinate is exactly between two pixels

### LINKED ISSUE #154: Stitch returns the wrong bounding box in the end
See the doc example, which gives out

~~~
SDM response → 450×1088 grid with 489600 Int64-valued cells
  Latitudes	43.18333333333334 ⇢ 43.65208333333334
  Longitudes	-80.00000000000001 ⇢ -70.93333333333335
~~~

where it should be

~~~
SDM response → 450×1088 grid with 489600 UInt8-valued cells
  Latitudes	43.18333333333334 ⇢ 46.93333333333335
  Longitudes	-80.00000000000001 ⇢ -70.93333333333335
~~~

### PR DESCRIPTION
**Pull request by tpoisot**
- [x] Do not use `stride` when clipping
    - Closes #150
- [x] Add options to `clip` to decide how to expand
    - Closes #151 
- [x] Test that clipping works with coordinates that are at the border of two pixels
    - Closes #149 
    - Redirects #152 to point to this branch
- [x] Closes #155 
    - Closes #154

### CODE REVIEW

**Comment by tpoisot** [comment]
OK, so this is a version that (i) does not use `stride` (ever) and (ii) uses `expand` to decide which side pixels to include.

@gabrieldansereau I think the next step is to write a bunch of tests to be sure this works, and then we can merge/tag.

**Comment by tpoisot** [comment]
(brought the new commits from `main` in - this means the GBIF issue with the deleted occurrence in the test is fixed)

**Comment by tpoisot** [comment]
@gabrieldansereau all yours, when you've done your review I will merge and tag

**Review by gabrieldansereau — CHANGES_REQUESTED** [review]
(This comment was meant to be BEFORE my previous commits)

This happens to fix the issue I mentioned in #152 when clipping with non-natural coordinates (with `cl1` in the tests). However, it brings back the same issues I fixed in #144 for natural ones, and I suspect it just happens to work with `cl1` but could possibly also bring issues with non-natural ones.

```julia
julia> M = rand(Bool, (10, 10));
       S = SimpleSDMPredictor(M, 0.0, 1.0, 0.0, 1.0);
       cl1 = clip(S; left = 0.2, right = 0.6, bottom = 0.5, top = 1.0) # all fine
SDM predictor → 5×4 grid with 20 Bool-valued cells
  Latitudes     0.5 ⇢ 1.0
  Longitudes    0.2 ⇢ 0.6

julia> M2 = rand(Bool, (1080, 2160));
       S2 = SimpleSDMPredictor(M2, -180.0, 180.0, -90.0, 90.0);
       exact_lats = (S2.bottom+1.0):1.0:(S2.top-1.0);
       all([isequal(l, clip(S2; top=l).top) for l in exact_lats]) # fails
       show([clip(S2; top=l).top for l in exact_lats])
[-89.0, -88.0, -87.0, -86.0, -85.0, -84.0, -83.0, -82.0, -81.0, -80.0, -79.0, -78.0, -77.0, -76.0, -75.0, -74.0, -73.0, -72.0, -71.0, -70.0, -69.0, -68.0, -67.0, -66.0, -65.0, -64.0, -63.0, -62.0, -61.0, -60.0, -59.0, -58.0, -57.0, -56.0, -55.0, -54.0, -53.0, -52.0, -51.0, -50.0, -49.0, -48.0, -47.0, -46.0, -45.0, -44.0, -43.0, -42.0, -41.0, -40.0, -39.0, -38.0, -36.99999999999999, -35.99999999999999, -35.0, -34.0, -33.0, -31.999999999999996, -30.83333333333333, -29.833333333333332, -29.0, -28.0, -26.83333333333334, -25.999999999999993, -24.999999999999993, -24.0, -23.0, -22.0, -21.0, -19.83333333333333, -18.83333333333333, -18.0, -17.0, -16.0, -14.999999999999993, -13.999999999999993, -13.0, -12.0, -11.0, -10.0, -8.833333333333329, -7.833333333333329, -7.0, -6.0, -5.0, -3.999999999999993, -2.999999999999993, -2.0, -1.0, 0.0, 1.0, 2.0, 3.000000000000014, 4.0, 5.0, 6.0, 7.0, 8.166666666666671, 9.000000000000014, 10.0, 11.0, 12.0, 13.0, 14.166666666666671, 15.0, 16.0, 17.0, 18.0, 19.16666666666667, 20.000000000000014, 21.0, 22.0, 23.0, 24.0, 25.16666666666667, 26.00000000000001, 27.000000000000004, 28.0, 29.0, 30.16666666666667, 31.00000000000001, 32.0, 33.0, 34.0, 35.0, 36.16666666666667, 37.000000000000014, 38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.0, 45.0, 46.0, 47.0, 48.0, 49.0, 50.0, 51.0, 52.0, 53.0, 54.0, 55.0, 56.0, 57.0, 58.0, 59.166666666666664, 60.0, 61.0, 62.0, 63.0, 64.0, 65.0, 66.0, 67.0, 68.0, 69.0, 70.0, 71.0, 72.0, 73.0, 74.0, 75.0, 76.0, 77.0, 78.0, 79.0, 80.0, 81.0, 82.0, 83.0, 84.0, 85.0, 86.0, 87.0, 88.0, 89.0]
```

From the last line I think there are two issues here. The most important one is that `clip(S2; top=8.0).top` returns `8.166666666666671` as the limit. This means one extra cell is included in the layer, so there would be an overlap if using that coordinate as `bottom` and `top` clip.

```julia
julia> clip(S2; top=8.0).top
8.166666666666671

julia> clip(S2; top=8.0) # should end at 8.0
SDM predictor → 589×2160 grid with 1272240 Bool-valued cells
  Latitudes     -90.0 ⇢ 8.166666666666671
  Longitudes    -180.0 ⇢ 180.0

julia> clip(S2; bottom=8.0) # should start at 8.0
SDM predictor → 492×2160 grid with 1062720 Bool-valued cells
  Latitudes     7.999999999999986 ⇢ 90.0
  Longitudes    -180.0 ⇢ 180.0
```

The 2nd issue is just a "display" one. The coordinate is not exactly the one used for clipping because of an approximation difference coming from `LinRange`, but the grid dimension is correct. Maybe this does not need to be fixed, but I think it would be nice to fix the display.

```julia
julia> clip(S2; top=3.0).top
3.000000000000014
```

**Comment by gabrieldansereau** [comment]
I fixed the issues and added some tests for them. It might not be necessary to test on every coordinate for a layer similar to the WorldClim 10 arcmin one as I'm doing here, but at least it's allowing us to catch all approximation errors.

I tried to clip with `gdalwarp` to validate my fix (for `top=8.0`), and now we have exactly the same layer dimensions and coordinates.

```julia
julia> l1 = SimpleSDMPredictor(RasterData(WorldClim2, BioClim));
       SpeciesDistributionToolkit.save("l1.tif", l1);
       run(`gdalwarp -te -180.0 -90.0 180.0 8.0 l1.tif l2.tif`);
       l2 = SpeciesDistributionToolkit._read_geotiff("l2.tif", SimpleSDMPredictor);
       l3 = clip(l1; top=8.0);

julia> size(l2) == size(l3)
true

julia> boundingbox(l2) == boundingbox(l3)
true

julia> l2 == l3
true
```

**Comment by tpoisot** [comment]
If this runs, can you add the test using `gdalwarp` (using the version that comes with `GDAL.jl`) to the tests and mark the review as approved?

**Comment by gabrieldansereau** [comment]
@tpoisot I added the code to test with `GDAL.jl,` but it requires writing and reading a layer, which is handled by SpeciesDistributionToolkit.

I think it's better to leave this as a test for SimpleSDMLayers only, so I commented out the GDAL-related code and tested directly with the layer dimensions that would be returned by GDAL.

**Review by gabrieldansereau — APPROVED** [review]

**Comment by tpoisot** [comment]
Cool, will merge -- can you open another PR to put the test at the top level of SpeciesDistributionToolkit (there is a folder for tests of edge cases, I think this qualifies)

**Pull request merged**
