### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by spaette**
Fauxcurrences/README.md
Fauxcurrences/src/bootstrap.jl
Fauxcurrences/src/utilities.jl
GBIF/src/occurrence.jl
GBIF/src/paging.jl
GBIF/src/types/GBIFRecords.jl
GBIF/test/occurrence.jl
README.md
SimpleSDMLayers/README.md
docs/src/SimpleSDMDatasets/index.md
docs/src/vignettes/occurrences/03_fauxcurrences.jl
src/integrations/gbif_layers.jl

### CODE REVIEW

**Comment by spaette** [comment]
no newline at end of file on some of the files in the patch

**Comment by tpoisot** [comment]
Thanks a lot!!

**Comment by spaette** [comment]
The Fragmented Forest
Larry D. Harris
© 1984 by The University of Chicago

A pioneering application of island biogeography theory.

<hr>

Tree Crops
by J. Russell Smith
1929

<hr>

Skogen och vår identitet
Erkki Lähde
Finlands Natur - 1984

The Forest and our Identity

Prof. Lähde recounts when as a young graduate out of forestry studies, he had the occasion to visit a village in the Finnish countryside. He noticed in the area a group of trees which to his view was overdue to be cut. But enquiring upon the local villagers of that stand of trees, the reply was that there was an old woman from the village who had liked to walk among that grove. Thus the trees were saved out of piety.

<hr>

In Normandy there's the use of the silvopasture method.

<hr>

Non-linear dynamics is a possibility for research in forest and land use policy.

**Comment by spaette** [comment]
The Fragmented Forest
Larry D. Harris
© 1984 by The University of Chicago

A pioneering application of island biogeography theory.

<hr>

Tree Crops
by J. Russell Smith
1929

<hr>

Skogen och vår identitet
Erkki Lähde
Finlands Natur - 1984

The Forest and our Identity

Prof. Lähde recounts when as a young graduate out of forestry studies, he had the occasion to visit a village in the Finnish countryside. He noticed in the area a group of trees which to his view was overdue to be cut. But enquiring upon the local villagers of that stand of trees, the reply was that there was an old woman from the village who had liked to walk among that grove. Thus the trees were saved out of piety.

<hr>

In Normandy there's the use of the silvopasture method.

<hr>

Non-linear dynamics is a possibility for research in forest and land use policy.

**Pull request merged**
