### PR TITLE
🐛 correct check on layer inner type

### LINKED ISSUE #145: IO not exported?
Am I missing a new change to the API or are the files in `./src/io` not exported? Is there another way to read/write from disk?

### PR DESCRIPTION
**Pull request by tpoisot**
Closes #145

### CODE REVIEW

**Comment by tpoisot** [comment]
@gottacatchenall use this branch to test and report back? I'll write an additional test to download/save/read a worldclim layer, or something like this

**Comment by gottacatchenall** [comment]
> @gottacatchenall use this branch to test and report back? I'll write an additional test to download/save/read a worldclim layer, or something like this

Currently throwing this
```ERROR: MethodError: Cannot `convert` an object of type Float32 to an object of type RasterCell{Float64, Float32}```

**Comment by tpoisot** [comment]
Got it. I'll write the test this evening, it shouldn't be a hard fix.

**Comment by tpoisot** [comment]
This should do the trick, as soon as it passes I'll tag a new patch release and you'll be good to go, @gottacatchenall

**Comment by gottacatchenall** [comment]
> This should do the trick, as soon as it passes I'll tag a new patch release and you'll be good to go, @gottacatchenall

can confirm this fixes the error [here](https://github.com/PoisotLab/SpeciesDistributionToolkit.jl/issues/145#issuecomment-1433562927)

**Pull request merged**
