### PR TITLE
Use CRS for SimpleSDMLayers

### PR DESCRIPTION
**Pull request by tpoisot**
This is a _big_ change, but it will help address some use-cases with BIAB work. This will lead to a switch from `v0.` to `v1.` for SimpleSDMLayers, and most likely a corresponding version change to the main package.

> [!note]
> This is the **pre-merge** checklist
> - [x] The vignettes are replaced by tutorials
> - [x] The smaller vignettes are replaced by how-tos
> - [x] There is a *runnable* Fauxcurrences example

> [!important]
> This is the **pre-release**, **post-merge** checklist
> - [ ] SimpleSDMLayers is tagged at `v1.0`
> - [ ] Fauxcurrences version increases to `v0.2` with a dependency upgrade
> - [ ] SpeciesDistributionToolkit is tagged with a new version and dependencies upgrades

### CODE REVIEW

**Comment by tpoisot** [comment]
Getting the docs to build is a little finicky when there are multiple versions of the packages that need to change their dependencies at the same time. Working on it.

**Comment by tpoisot** [comment]
I think I got it!

**Comment by tpoisot** [comment]
I'm going to leave this open for a few days just so @gottacatchenall and maybe @gabrieldansereau can have a look, but this is the new version with CRS built-in.

It's a pretty major change, so some features have temporarily been removed (like masking from polygons).

**Comment by gottacatchenall** [comment]
Cool, proj seems to work well for quickly transforming crs, is the idea to add a function that does bilinear (or whatever) interpolation on a result like below to convert it back to a raster? image

**Comment by tpoisot** [comment]
> Cool, Proj.jl seems to work well for quickly transforming crs, is the idea to add a function that does bilinear (or whatever) interpolation on a result like below to convert it back to a raster?

Post merge, almost definitely; just so I'm clear about what it entails, what kind of workflow/use-case do you have in mind?

**Comment by tpoisot** [comment]
@gottacatchenall there's this now https://poisotlab.github.io/SpeciesDistributionToolkit.jl/previews/PR227/howto/interpolate.html

**Comment by gottacatchenall** [comment]
> @gottacatchenall there's this now https://poisotlab.github.io/SpeciesDistributionToolkit.jl/previews/PR227/howto/interpolate.html

Okay great!

> Post merge, almost definitely; just so I'm clear about what it entails, what kind of workflow/use-case do you have in mind?

I was mostly looking for it as a quality of life improvement because the easiest way to reproject prior was to write a tiff and use ArchGDAL internals. 

Only a couples things before I think we should merge and tag so this can be used for https://github.com/GEO-BON/bon-in-a-box-pipelines/issues/168:

- As far as I can tell we no longer need to write out EPSG:4326?  ([here](https://github.com/PoisotLab/SpeciesDistributionToolkit.jl/blob/878e56360ebe7b1415f122b29fbb3bb4a518f5e2/src/io/geotiff.jl#L223)) 
- Lingering `@info` call here https://github.com/PoisotLab/SpeciesDistributionToolkit.jl/blob/878e56360ebe7b1415f122b29fbb3bb4a518f5e2/SimpleSDMLayers/src/interpolation.jl#L20
- Does `io` make sense at the `SpeciesDistributionToolkit` level? If you only import `SimpleSDMLayers` you can't call [`save`](https://github.com/PoisotLab/SpeciesDistributionToolkit.jl/blob/878e56360ebe7b1415f122b29fbb3bb4a518f5e2/src/io/read_write.jl#L21), would it make more sense to define it in `SDMLayers` and reexport from `SDT`?
- There's now a bit of namespace ambiguity around `Projection` https://github.com/PoisotLab/SpeciesDistributionToolkit.jl/blob/71c849174a80c09b3dfa7b6af2d49d01d195e04a/SimpleSDMDatasets/src/types/specifiers.jl#L30 for future scenarios, not urgent though

**Comment by tpoisot** [comment]
good points -I've moved the code around, give me a minute to make sure it still works

**Comment by gottacatchenall** [comment]
Oh another minor thing, likely not necessary before this is merged: I can imagine a few edges cases where storing the `SDMLayer` `indices` field as a BitMatrix instead of a SparseMatrix could be very memory inefficient. Probably not super high priority

**Comment by tpoisot** [comment]
I might have to do one more substantial change before this is ready - we're storing the CRS as "whatever", but using JuliaGeo/GeoFormatTypes.jl would make sense here

**Comment by tpoisot** [comment]
> Oh another minor thing, likely not necessary before this is merged: I can imagine a few edges cases where storing the `SDMLayer` `indices` field as a BitMatrix instead of a SparseMatrix could be very memory inefficient. Probably not super high priority

definitely, but this is solveable after by allowing a different type of matrix (indexing will be the same anyway)

**Comment by tpoisot** [comment]
@gottacatchenall I think we can merge and get started on the BRT pipeline?

**Comment by gottacatchenall** [comment]
Looks good to me

**Pull request merged**
