### PR TITLE
removing unnecessary(?) return in  `_write_geotiff`

### PR DESCRIPTION
**Pull request by gottacatchenall**
this fixes permission issues in docker that exist for unknown reasons re https://github.com/GEO-BON/bon-in-a-box-pipelines/pull/170#issuecomment-2369430007

### CODE REVIEW

**Comment by tpoisot** [comment]
Can you check what's going on with these changes?

**Comment by gottacatchenall** [comment]
all the test pass locally for me with the `write` commented out, what part isn't working?

**Comment by jmlord** [comment]
> all the test pass locally for me with the `write` commented out, what part isn't working?

It looks like it was cancelled more than failed:
image

**Comment by tpoisot** [comment]
I dropped a full method that wasn't used anymore, and then I think this is ready to go.

**Pull request merged**
