### PR TITLE
compression/format kwargs for geotiffs

### LINKED ISSUE #160: geotiff driver kwarg
In https://github.com/PoisotLab/SpeciesDistributionToolkit.jl/issues/30#issuecomment-1314513569 we discussed having an option to save with different geotiff drivers (needed for cloud-optimizer-geotiff (COG), see https://github.com/GEO-BON/biab-2.0/pull/40#discussion_r1117644273).

I don't think this is currently implemented, but would be as simple as moving the argument to this call https://github.com/PoisotLab/SpeciesDistributionToolkit.jl/blob/4c63b82698366e025612791b5f3c3e36005661df/src/io/geotiff.jl#L223 to be a keyword arg to `save` that is passed onto `_write_geotiff`

### PR DESCRIPTION
**Pull request by gottacatchenall**
Closes #160 - support to specify the geotiff driver

### CODE REVIEW

**Comment by tpoisot** [comment]
Is there a list of supported drivers that we could check against before trying to use them?

**Comment by gottacatchenall** [comment]
GDAL provides a list of supported drivers [here](https://gdal.org/drivers/raster/index.html), although it's possible ArchGDAL or typical GDAL distributions don't support them all

**Comment by tpoisot** [comment]
I'm looking at that table like

Screen_Shot_2020-07-24_at_11 33 38_AM

**Comment by tpoisot** [comment]
but maybe we can stick to the "built-in by default"?

**Comment by tpoisot** [comment]
GDAL has a list of drivers here: https://github.com/JuliaGeo/GDAL.jl/blob/040bda4ac1b57fbd18239036f08c8b8fcf06849e/test/drivers.jl

So we can stick them in a const, and check that the driver matches.

**Comment by gottacatchenall** [comment]
nice! spatial projection change could also be as easy as an arbitrary kwarg if GDAL/ArchGDAL has a list of valid EPSGs, i can check if they do

**Comment by tpoisot** [comment]
So, `ArchGDAL.listdrivers()` should get us the valid driver names. We can work on the valid EPSGs later.

**Review by tpoisot — APPROVED** [review]

**Pull request merged**
